### PR TITLE
Feature startup guide changes to run frontend

### LINKED ISSUE #77: Repair startup guide for frontend
Figure out the issue some people are have with starting the frontend react application. 'React-scripts' is not installed etc.

### PR DESCRIPTION
**Pull request by elliot-mb**
# Changes
## README.md
- Added prerequizite that you need to run ``npm install`` to install the dependencies. 
Closes #77

### CODE REVIEW

**Review by fo21 — APPROVED** [review]
guide changes look alright

**Comment by elliot-mb** [comment]
@fo21 do they happen to work for you?

**Review by BadrTM — APPROVED** [review]
Works for me

**Comment by fo21** [comment]
@elliot-mb no, but I had it running just fine at some point

**Pull request merged**
